version: "3.9"
services:
  reverse-proxy:
    depends_on:
      - keycloak
    image: nginx:alpine
    restart: always
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse-proxy/ssl:/etc/ssl
    ports:
    - "80:80"
    - "443:443"
  jenkins:
    build: ./jenkins/.
    privileged: true
    environment:
      JENKINS_PREFIX: /jenkins
      JENKINS_OPTS: "--prefix=/jenkins"
      JENKINS_USER: admin
      JENKINS_PASS: admin
    ports:
    - "9090:8080"
    - "50000:50000"
    container_name: jenkins
    volumes:
     - jenkins_data:/var/jenkins_home
     - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
     - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_data:

