version: "3.9"
services:
  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  keycloak:
    depends_on:
      - db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_PROXY: edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: false #deactivate fixed hostname
      KC_HOSTNAME_STRICT_HTTPS: false #For local access to console admin in start mode
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_PATH: /auth
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: localhost
      KC_HOSTNAME_ADMIN_URL: https://localhost/auth/
    image: quay.io/keycloak/keycloak:24.0
    command: ["start-dev", "--import-realm"]
    volumes:
      - ./keycloak/realms/:/opt/keycloak/data/import/:ro
      - ./keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-2fa-email-authenticator-1.0.0.0-SNAPSHOT.jar
      # - ./keycloak/templates/html/code-email.ftl:/opt/keycloak/themes/base/email/html/code-email.ftl:ro
      # - ./keycloak/templates/text/code-email.ftl:/opt/keycloak/themes/base/email/text/code-email.ftl:ro
   
    ports:
    - "8080:8080"
  reverse-proxy:
    depends_on:
      - keycloak
    image: nginx:alpine
    restart: always
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./reverse-proxy/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./reverse-proxy/nginx-selfsigned.key:/etc/ssl/certs/nginx-selfsigned.key
      - ./reverse-proxy/dhparam.pem:/etc/ssl/certs/dhparam.pem
    ports:
    - "80:80"
    - "443:443"
  web:
    depends_on:
      - keycloak
    image: nginx:alpine
    restart: always
    volumes:
      - ./web/data:/data:ro
      - ./web/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
    - "8888:80"
  mail:
    image: bytemark/smtp
    restart: always
  jenkins:
    build: ./jenkins/.
    privileged: true
    environment:
      JENKINS_PREFIX: /jenkins
      JENKINS_OPTS: "--prefix=/jenkins"
      JENKINS_USER: admin
      JENKINS_PASS: admin
    ports:
    - "9090:8080"
    - "50000:50000"
    container_name: jenkins
    volumes:
     - ./jenkins/data:/var/jenkins_home
     - ./jenkins/casc.yaml:/var/jenkins_home/casc.yaml
     - /var/run/docker.sock:/var/run/docker.sock
volumes:
  postgres_data:

